language: node_js # 设置语言
node_js: stable # 设置相应版本
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容
install:
    - npm install # 安装hexo及插件
    - npm rebuild node-sass --force #该命令是根据构建失败的日志提示添加的
    - npm install hexo-deployer-git --save
before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - npm uninstall hexo-cli -g
    - npm install hexo-cli -g  # 安装hexo环境
    #- chmod +x ./publish-to-gh-pages.sh  # 为shell文件添加可执行权限
after_script:
    - ./publish-to-gh-pages.sh
script:
    - hexo clean # 清除
    - hexo g # 生成
branches:
    only:
        - dev # 只监测dev分支
env:
    global:
        # Github Pages
        - GH_REF: https://github.com/luochenxi/luochenxi.github.io.git #设置GH_REF，注意更改成自己的仓库地址
